### ISSUE TITLE
Docs out of date

### ISSUE THREAD

**Issue by baolongt** [ICPSwap-Labs/docs#1]
[docs](https://github.com/ICPSwap-Labs/docs/blob/main/03.SwapInformation/03.Fetching_Token_Info.md#reading-token-price-chart-data)
The `getTokenPricesData` is removed, I believed

**Comment by HeliosF** [comment]
No, it's not.
<img width="1045" alt="doc" src="https://github.com/ICPSwap-Labs/docs/assets/17735250/5634278f-e5c2-4430-a4c6-af477db93ac7">
<img width="977" alt="canister ui" src="https://github.com/ICPSwap-Labs/docs/assets/17735250/fc98110a-b039-4bd3-ad79-2b42063e892b">

**Comment by HeliosF** [comment]
No, it's not.
<img width="1045" alt="docs" src="https://github.com/ICPSwap-Labs/docs/assets/17735250/8f2ebb5b-ff01-4611-b058-af0da3bd2791">
<img width="977" alt="canister ui" src="https://github.com/ICPSwap-Labs/docs/assets/17735250/3b2db569-46c9-416c-9bc3-4c870a39b880">
