### ISSUE TITLE
[doc] Doc for getUserPositionWithTokenAmount pool canister

### ISSUE THREAD

**Issue by baolongt** [ICPSwap-Labs/docs#2]
I tried to get data from getUserPositionWithTokenAmount but seems it doesn't have a docs

**Comment by HeliosF** [comment]
Because this method will return an error like 'IC0522: Canister xxx exceeded the instruction limit for single message execution' when querying too many positions. So we recommend to do token amount calculation outside the pool, and there is no corresponding documentation provided for its use.
