### ISSUE TITLE
Liquidity pool create

### ISSUE THREAD

**Issue by baolongt** [ICPSwap-Labs/docs#4]
There is the doc for minting the pool. 

https://github.com/ICPSwap-Labs/docs/blob/main/02.SwapPool/Liquidity/01.Minting_a_Position.md

But I'm looking for create a liquidity pool that not exist yet. Does icpswap have this?

**Comment by HeliosF** [comment]
Not yet, coming in the future.

**Comment by baolongt** [comment]
@HeliosF How long for waiting. I'm curious

**Comment by HeliosF** [comment]
> @HeliosF How long for waiting. I'm curious

In the plan, but there are other higher priority tasks at the moment, thanks for your patient sir.

**Comment by HeliosF** [comment]
> @HeliosF How long for waiting. I'm curious

https://github.com/ICPSwap-Labs/docs/blob/main/01.SwapFactory/02.Creating_a_Pool.md
Here is the doc of creating a pool.
